### ISSUE TITLE
feature: support various CR cost allocation insights

### ISSUE THREAD

**Issue by mrhello369** [kubefin/kubefin#3]
> /area API

## Describe the feature

As a user, I may have different custom resources, such as Knative(https://knative.dev/docs/getting-started/first-service/):
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
```
So I want the cost allocation insights at knative service level.
